### ISSUE TITLE
Explanation: If keys are not found

### ISSUE THREAD

**Issue by AnaisUrlichs** [near-examples/near-account-utils#1]
After running "yarn keys" all keys that are not accessible locally are not found. 

It would be great to have an explanation of why keys are not found and whether that is "a bad thing".
Right now the user is left a bit hanging.

**Comment by tucq88** [comment]
Have the same issue, I have plenty of keys in `~/.near-credentials/testnet/` but `yarn keys` display none :( 

For e.g https://gyazo.com/65b45cf456e200060c584537258c4e3f
